[window]

startup_mode = "Windowed"

padding.x = 0
padding.y = 0

decorations = "Transparent"
decorations_theme_variant = "Dark"

opacity = 0.8

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"
size = 16.0

# cyberdream theme for alacritty
[[colors.indexed_colors]]
color = "0xffbd5e"
index = 16

[[colors.indexed_colors]]
color = "0xff6e5e"
index = 17

[colors.bright]
black = "0x3c4048"
blue = "0x5ea1ff"
cyan = "0x5ef1ff"
green = "0x5eff6c"
magenta = "0xbd5eff"
red = "0xff6e5e"
white = "0xffffff"
yellow = "0xf1ff5e"

[colors.normal]
black = "0x16181a"
blue = "0x5ea1ff"
cyan = "0x5ef1ff"
green = "0x5eff6c"
magenta = "0xbd5eff"
red = "0xff6e5e"
white = "0xffffff"
yellow = "0xf1ff5e"

[colors.primary]
background = "0x16181a"
foreground = "0xffffff"

[colors.selection]
background = "0x3c4048"
foreground = "0xffffff"
